title       = "hf"
baseURL     = "https://hf-cli.tamnd.com/"
description = "A command line for Hugging Face."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/hf-cli"
